name: CI

on: [push]
jobs:
  job:
    name: ${{ matrix.os }}-cmake-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
#        include:
#          - os: windows-latest
#            CC: gcc

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get -y install libglm-dev libglfw3-dev libglew-dev mesa-common-dev
        if: "contains( matrix.os, 'ubuntu')"
      - name: run-cmake
        uses: lukka/run-cmake@v2.4
        if: "!contains( matrix.os, 'windows')"
      - name: Run CMake+MinGW-w64
        uses: lukka/run-cmake@v2.4
        if: "contains( matrix.os, 'windows')"
        with:
          buildDirectory: '${{ runner.workspace }}/b/mingw-w64'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: '-G "Ninja" -DWITH_ALSA=No -DWITH_PULSEAUDIO=No -DWITH_JACK=No'